version: "3"
services:
  app:
    container_name: mainApp
    restart: always
    build: ./api
    ports:
      - "4000:4000"
    depends_on:
      - mongo
  client:  
    container_name: mainClient
    restart: always
    build: ./client
    ports:
      - "3000:3000"
    links:
      - app
  mongo:
    container_name: mongoApp
    image: mongo
    restart: always
    expose:
      - "27017"
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
